### ISSUE TITLE
Deeper Chamber.to_s

### ISSUE THREAD

**Issue by moubry** [thekompanee/chamber#37]
If you have a YAML file with this content:

```
foo: bar
movies:
  - title: Jurassic Park
    year: 1993
  - title: Minority Report
    year: 2002
```

Then `Chamber.to_s` will output:

```
FOO="bar"
MOVIES="[#, #]"
```

It'd be awesome if Chamber outputted keys/values of the hashes inside the movies array too.

**Comment by jfelchner** [comment]
@moubry thanks for the patience.  Chamber has been working solidly for me and I haven't given it much more attention.  Are you still using it and if so, is this still a problem for you?

**Comment by moubry** [comment]
Thanks for the follow-up. Embarrassingly, I don’t even remember opening this issue. You can go ahead and close it — doesn’t seem like most users have the problem — I certainly don’t anymore.

**Comment by jrochkind** [comment]
I found this cause I'm interested in hash values in Chamber. Any thoughts?

**Comment by jfelchner** [comment]
@jrochkind you're going to need to elaborate.

**Comment by jrochkind** [comment]
Much like the OP, I'm interested in having Chamber keys that are Hash values, or arrays of Hash values. Possibly multiple levels. 

```yaml
some_hash:
  foo: bar
  baz: whatever
some_array_of_hash:
  - title: whatever
     people:
        - john
        - eduardo
```
