### ISSUE TITLE
Secure values must be strings?

### ISSUE THREAD

**Issue by jdickey** [thekompanee/chamber#41]
Modifying the as-generated `config/settings.yml` file as follows:

```yaml
development:
  setting:                development_value
  # The following will become 'secure_setting'
  _secure_forty_twoish_setting:       41
  _secure_setting: secure_development_value

test:
  setting:                test_value
  # The following will become 'secure_setting'
  _secure_forty_twoish_setting:       42
  _secure_setting: secure_test_value

production:
  setting:                production_value
  _secure_forty_twoish_setting:       43
  # The following will become 'secure_setting'
  _secure_setting: secure_production_value
```

and running `bundle exec chamber init` will create output similar to

```
$ bundle exec chamber secure
     encrypt  DEVELOPMENT_SETTING
     encrypt  PRODUCTION_SETTING
     encrypt  TEST_SETTING
$
```

No change to the "_secure_fortytwoish_setting" values will be made. YAML is a *lot* more than just strings-in-hashes; did I miss a note in the documentation that only simple strings are supported?
