### ISSUE TITLE
Overriding Shared values doesn't work

### ISSUE THREAD

**Issue by oozzal** [thekompanee/chamber#44]
I have the following settings in `config/settings/redis.yml`

```
default: &shared
  redis:
    port: 6379

development:
  <<: *shared
  redis:
    host: localhost
...
```

But when I access `Chamber.redis`, it gives me the following:

``` ruby
{"host" => "localhost"}
```

As you can see, the value of `port` from shared is missing.

From [this](https://github.com/thekompanee/chamber/wiki/Organizing-Your-Settings#full-example) wiki, I can tell that it's a bug and not a feature.

@jfelchner @m5rk

**Comment by jfelchner** [comment]
@oozzal thanks for the report.  I'll take a look!

**Comment by jfelchner** [comment]
@oozzal sometimes the `Chamber.` notation acts strangely.  Try: `Chamber.env.redis` and see if that works.

**Comment by oozzal** [comment]
@jfelchner `Chamber.env.redis` doesn't work either.

**Comment by jfelchner** [comment]
@oozzal I'm using this notation consistently and it works for me.  Let me try to dig into it a bit more.

**Comment by bmedici** [comment]
@oozzal seems to be a well-known 'bug' from the YAML parser, when merging already initlalized sections.
Really annoying as we cannot partially initialize some parameters and continue in a deeper config file.
I have mentionnend the bug in some of my projects (eg [rest-ftp-daemon)](https://github.com/bmedici/rest-ftp-daemon) in  Known bugs

**Comment by jfelchner** [comment]
@bmedici what specifically is the bug?  I'm doing exactly (or so it appears) what @oozzal is doing in his snippet above and it's working fine for me. :(

**Comment by jfelchner** [comment]
@oozzal I finally tracked down what you need to do here.  This is, indeed, as @bmedici mentioned, YAML behavior and nothing specifically that Chamber is doing.

What you'd want to do would be:

```yaml
defaults:
  redis: &shared_redis
    port:     1234

development:
  redis:
    <<: *shared_redis
    host: localhost

test:
  redis:
    <<: *shared_redis
    host: localhost2
```

which should get you the result you wanted.
