### ISSUE TITLE
Q: staging settings deployed to a staging app in heroku?

### ISSUE THREAD

**Issue by BKSpurgeon** [thekompanee/chamber#70]
Hi there

Thank you for this work: it is very clear to me that a lot of thought and effort has gone into the gem and also the documentation is very, very good <3

A question that I have:

```yaml
development:
  host: "localhost:3000"
  
test: 
  host: "localhost:3000"

production:  
  host: "production.herokuapp.com"

staging:  
  host: "staging.herokuapp.com"
```

* From what I read, chambers will pick up whether i am in the development, test and production environments, and load the appropriate key-values. But what about staging? There is a `staging` namespace above. I have a corresponding heroku app that is a `staging` app. I want the staging app to pick up the staging namespace keys, and I want the production version of the app (which is a different app entirely) to pick up the production version of the keys: how can i do this?

(I did have a good go at looking and reading the documentation, but I did not fully understand everything that I read, hence I am resorting to opening up an issue on Github).

Any pointers in the right direction would be much appreciated. I am happy to make PRs, documentation changes etc. to clarify things if required.

Thank you so much.

rgds

Ben
