### ISSUE TITLE
extended Chamber class does not load custom initializer/namespaces

### ISSUE THREAD

**Issue by dali546** [thekompanee/chamber#71]
## Current Behavior
https://github.com/thekompanee/chamber/issues/63 outlines how to define custom namespaces which I have done. However when I extend the Chamber module
```ruby
class Settings
  extend Chamber
end
```
`Settings` does not load the keys defined in my custom namespaces

### Steps to Reproduce

```ruby
class MyApp
  class Application < Rails::Application
    Chamber.load basepath: ::Rails.root.join('config'),
                    namespaces: {
                      environment: -> { ::Rails.env },
                      domain:      -> { ENV['CUSTOM_NAMESPACE'] }
                      hostname:    -> { ::Socket.gethostname }
                    }
  end
end
```
```yaml
# config/settings/foo.yml
development:
  foo: A Common Key Not Leveraging My Custom Namespace
...
# config/settings/foo-bar.yml
development:
  foo: A Key When My Custom Namespace is bar
...
# config/settings/foo-baz.yml
development:
  foo: A Key When My Custom Namespace is baz
```

When I have CUSTOM_NAMESPACE set to 'bar', I get the following output
```ruby
Loading development environment (Rails 5.1.2)
irb(main):001:0> Settings.to_s
=> "FOO=\"A Common Key Not Leveraging My Custom Namespace\""
irb(main):002:0> Chamber.to_s
=> "FOO=\"A Key When My Custom Namespace is bar\""
```
## Expected Behavior
I expect Settings class to load the configuration based on my custom Chamber initializer and namespaces.

A related issue is also it's not documented where to define `Settings`. I have defined it in `config/environment.rb`.

## Environment

Rails: 5.1.2
Chamber: 2.13.1
